# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    demo_user.registration_listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

   # demo_user.login_success_handler:
    #    class: AppBundle\EventListener\LoginSuccessHandler
   #     arguments: 
  #          - router
 #           - security.context
#
  #      tags:
  #          - { name: monolog.logger, channel: security }

     